"""
Sphinx configuration for caldav-cal-api.

The API pages are generated by sphinx-apidoc as a ReadTheDocs pre_build step (see
.readthedocs.yaml), so caldav_cal_api.rst and caldav_cal_api.utils.rst are produced at
build time rather than committed.
"""

import os
import sys

# The package lives two levels up from docs/source, and autodoc imports it for real.
sys.path.insert(0, os.path.abspath("./../.."))

project = "CalDAV-Cal-API"
copyright = "2026, thiswillbeyourgithub"
author = "thiswillbeyourgithub"
release = "0.1.1"  # Kept in sync by bumpver.

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "myst_parser",  # Lets the prose pages be written in Markdown.
    "sphinx.ext.autosectionlabel",
]

# The package __init__ re-exports the data classes for convenience. Without this,
# automodule honours its __all__ and documents each class twice (once as
# caldav_cal_api.EventData, once as caldav_cal_api.utils.data.EventData), which makes
# every bare :class:`EventData` reference ambiguous. Ignoring __all__ restricts each
# module page to what that module actually defines.
autodoc_default_options = {"ignore-module-all": True}
autodoc_member_order = "groupwise"
autodoc_typehints = "signature"
autodoc_inherit_docstrings = True

# The codebase uses NumPy-style docstrings; Google support is left on so that a snippet
# copied from the sibling project still renders correctly.
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True

# autosectionlabel across many Markdown files would otherwise collide on common headings.
autosectionlabel_prefix_document = True

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

templates_path = ["_templates"]
exclude_patterns = []

html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "show_nav_level": 2,
    "navigation_depth": 3,
}
html_static_path = []
